language: python
python:
      - "3.6"
install:
      - pip install -r requirements.txt
before_script:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
    fi

script:
      - pytest -v --pep8
